### ISSUE TITLE
No versions for latest releases images

### ISSUE THREAD

**Issue by SamyCoenen** [automationbroker/apb#152]
When running apb inside of a container, to use versions above v2, you need to use docker.io/ansibleplaybookbundle/apb-tools:nightly

Instead there should be tags for every release.

Right now an alternative is using the digest after checking the version manually.

`skopeo inspect docker://docker.io/ansibleplaybookbundle/apb-base:nightly | jq .Digest`

**Comment by SamyCoenen** [comment]
I discovered that Red Hat customers can use the Red Hat registry
registry.redhat.io/openshift4/apb-tools:v4.1.0 equals apb-2.0.3

**Comment by jmrodri** [comment]
@SamyCoenen thank you for submitting this issue. The apb tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.

The apb-tools from the Red Hat registry will continue to be supported following the OpenShift support policy.
