### ISSUE TITLE
Add capability to load APB params from file

### ISSUE THREAD

**Issue by djwhatle** [automationbroker/apb#90]
It would be cool to have an option to specify APB params within a simple YAML or JSON file, and then feed those params into an APB action like so:

```
$ apb provision mysql-apb --params mysql.yaml
Starting provision pod for [mysql-apb]...
```
where mysql.yaml looks like:
```
mysql-username: admin
mysql-version: 9.6
[...]
```

We could allow users to create these parameter files either by hand, or by entering params within the tool and saving off the result.

```
$ apb provision mysql-apb --export-params mysql.yaml --dry-run
Enter value for [mysql-username]: 
Enter value for [mysql-version]:
[...]
Saved params to mysql.yaml
Not running provision action since --dry-run was specified
```

**Comment by ron1** [comment]
Since the apb tool includes a bundle provision capability, the functionality of this feature should be comparable to the corresponding Service Catalog {{svcat provision}} feature described here: https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/cli.md#provision-a-service that includes support for flags --param, --secret, and --params-json.

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
